- name: Install nginx
  apt:
    name: nginx-core

- name: Configure custom index page
  template:
    src: roles/nginx/templates/index.html
    dest: /var/www/html/index.html

# - name: Configure nginx as a frontend for uWSGI
#   template:
#     src: roles/nginx/templates/config
#     dest: /etc/nginx/sites-enabled/default
#   notify:
#   - Restart nginx
