- name: Get telegraf package
  apt:
    deb: https://dl.influxdata.com/telegraf/releases/telegraf_1.16.3-1_amd64.deb

- name: Install InfluxDB and client packages
  apt:
    name: 
      - influxdb
      - influxdb-client
    update_cache: yes

- name: Configure Telegraf
  template:
    src: roles/influxdb/templates/telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  notify:
    - Restart telegraf

- name: Have influxdb start on boot
  service:
    name: influxdb
    state: started

- name: Have telegraf start on boot
  service:
    name: telegraf
    state: started


# make latency db by using commands "influx", "create database latency", and "use latency"