- name: Configure rsyslog
  template:
    src: roles/rsyslog/templates/50-telegraf.conf
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify: Restart rsyslog

- name: start on boot
  service:
    name: rsyslog
    state: started