- name: Create place for docker file
  file:
    path: /opt/agama
    state: directory

- name: Install some thing
  apt:
    name: python3-pymysql
    
- name: Download dockerfile
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile

- name: Build docker image
  docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama
      network: host

- name: Run agama in docker container
  docker_container:
    name: agama
    image: agama
    state: started
    published_ports:
      - "{{ agama_port }}:8000"
    env:
      AGAMA_DATABASE_URI: mysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}