- name: Install fping
  apt:
    name: fping
    state: present

- name: Create pinger user to execute service
  user:
    name: "{{ pinger_user }}"
    password: "{{ pinger_password }}"
    state: present
    system: yes

- name: Add pinger script
  template:
    src: roles/pinger/templates/pinger
    dest: /usr/local/bin/pinger
    mode: '0755'
  notify: 
    - Restart influxdb

- name: Create a directory if it does not exist
  file:
    path: /etc/pinger
    state: directory

- name: Add pinger configuration
  template:
    src: roles/pinger/templates/pinger.conf
    dest: /etc/pinger/pinger.conf
  notify: 
    - Restart influxdb

- name: Create pinger service
  template:
    src: roles/pinger/templates/service
    dest: /etc/systemd/system/pinger.service
    mode: '0644'
  notify:
    - Reload daemon
    - Restart pinger

- name: Pinger is started on boot
  service:
    name: pinger
    state: started