---
- name: Setup
  hosts: all
  tasks:
    - setup:  
  
- name: Configure bind
  hosts: dns_server
  become: yes
  roles:
    - bind
  tags:
    - bind
  handlers:
    - name: Reload rndc
      shell:
        cmd: rndc reload
    - name: Restart bind
      service:
        name: bind9
        state: restarted
- name: Configure DNS to resolve backup server
  hosts: all
  become: yes
  roles:
    - dns
  tags:
    - dns
  handlers:
    - name: Restart systemd-resolved
      service:
        name: systemd-resolved
        state: restarted

  
- name: Add backup user to all machines
  hosts: all
  become: yes
  roles:
    - backup
  tags:
    - backup
    
