---
  - name: Setup
    hosts: all
    tasks:
      - setup:
  
  - name: Bind
    hosts: dns_server
    become: yes
    roles:
      - bind

  - name: Resolvers
    hosts: all
    become: yes
    roles:
      - dns
      - node_exporter

  - name: Prometheus
    hosts: prometheus
    become: yes
    roles:
      - prometheus
  