---
- name: Setup
  hosts: all
  tasks:
    - setup:

- name: Bind setup
  hosts: dns_server
  become: yes
  roles:
    - bind
    - bind_exporter
  tags:
    - dns

- name: Resolver setup
  hosts: all
  become: yes
  roles:
    - dns
    - node_exporter
  tags:
    - dns

- name: MySQL server and exporter
  hosts: db_servers
  become: yes
  roles:
    - mysql
    - mysql_exporter
  tags:
    - mysql

- name: Agama
  hosts: app_servers
  become: yes
  roles:
    - agama
    - uwsgi
    - nginx
    - nginx_exporter
  tags:
    - agama

- name: Backup
  hosts: all
  become: yes
  roles:
    - backup
  tags:
    - backup

- name: Prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus
  tags:
    - prometheus

- name: Grafana
  hosts: grafana
  become: yes
  roles:
    - grafana
  tags:
    - grafana
