{
 "title": "Infra",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "appname",
    "label": "Appname",
    "query": "SHOW TAG VALUES FROM syslog WITH KEY=appname"
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "SHOW TAG VALUES FROM syslog WITH KEY=hostname"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "SHOW TAG VALUES FROM syslog WITH KEY=severity"
   },
   { "name": "Query", "label": "Query" }
  ]
 },
 "panels": [
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu{mode!=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable" }
   ]
  },
  { "title": "Bind", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Master Bind status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "bind_up" }
   ]
  },
  {
   "title": "DNS queries per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bind_incoming_queries_total{instance=\"ellawerthan-3.hitec.io:9119\"}[1m])"
    }
   ]
  },
  {
   "title": "Slave1 Bind status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "bind_up" }
   ]
  },
  {
   "title": "DNS queries per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bind_incoming_queries_total{instance=\"ellawerthan-1.hitec.io:9119\"}[1m])"
    }
   ]
  },
  {
   "title": "Slave2 Bind status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "bind_up" }
   ]
  },
  {
   "title": "DNS queries per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bind_incoming_queries_total{instance=\"ellawerthan-2.hitec.io:9119\"}[1m])"
    }
   ]
  },
  { "title": "MySQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Slave Server ID",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id"
    }
   ]
  },
  {
   "title": "MySQL Slave status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "MySQL queries per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{instance=\"ellawerthan-2.hitec.io:9104\"}[1m])"
    }
   ]
  },
  {
   "title": "Server ID",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id"
    }
   ]
  },
  {
   "title": "MySQL status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "MySQL queries per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{instance=\"ellawerthan-1.hitec.io:9104\"}[1m])"
    }
   ]
  },
  { "title": "haproxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "haproxy1 status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "haproxy_up" }
   ]
  },
  {
   "title": "keepalived1 status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "keepalived_up" }
   ]
  },
  {
   "title": "keepalived1 status",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 49 },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"ellawerthan-1.hitec.io:9165\"}"
    }
   ]
  },
  {
   "title": "haproxy2 status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "haproxy_up" }
   ]
  },
  {
   "title": "keepalived2 status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "keepalived_up" }
   ]
  },
  {
   "title": "keepalived2 status",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 55 },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"ellawerthan-2.hitec.io:9165\"}"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Nginx status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "Nginx requests per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])"
    }
   ]
  },
  { "title": "Influxdb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "dst" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Syslog count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "none", "label": "Messages / min" }
   ],
   "targets": [
    {
     "alias": "Info",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "query": "SELECT count(\"severity_code\") FROM \"syslog\" WHERE (\"severity\" = 'info' AND \"hostname\" =~ /^$hostname$/ AND \"severity\" =~ /^$severity$/ AND \"appname\" =~ /^$appname$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "info" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
     ]
    },
    {
     "alias": "Notice",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "notice" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
     ]
    },
    {
     "alias": "Warning",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "warning" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
     ]
    },
    {
     "alias": "Error",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "err" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
     ]
    },
    {
     "alias": "Critical",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "crit" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
     ]
    },
    {
     "alias": "Alert",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "alert" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
     ]
    },
    {
     "alias": "Emergancy",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "emerg" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
     ]
    }
   ]
  },
  {
   "title": "Syslog messages",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "appname" ], "type": "tag" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" }
      ],
      [
       { "params": [ "message" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" }
     ]
    }
   ]
  }
 ]
}