---
- name: Add user backup to machines
  user:
    name: backup
    generate_ssh_key: yes
    state: present
    home: /home/backup
    shell: "/bin/bash"
    ssh_key_file: .ssh/id_rsa

- name: Add backup directory
  file:
    path: /home/backup/backup
    state: directory
    owner: backup
    group: backup
    mode: '0755'

- name: Add restore directory
  file:
    path: /home/backup/restore
    state: directory
    owner: backup
    group: backup
    mode: '0755'

- name: Install duplicity to machines
  apt:
    name: duplicity
    state: present

- name: Schedule backup scripts for MySQL machines
  template:
    src: backup
    dest: /etc/cron.d/backup
  when: inventory_hostname in groups['db_servers']