---
- name: Restart bind
  service:
    name: bind9
    state: restarted

- name: Reload rndc
  shell:
    cmd: rndc reload

- name: Restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted