- name: Install docker and friends
  apt:
    pkg:
      - docker.io
      - python3-docker
    update_cache: yes
    # upgrade: yes

- name: Make sure docker is running and started on boot
  service:
    name: docker
    enabled: yes
    state: started
