---
- name: Add user backup to machines
  user:
    name: backup
    generate_ssh_key: yes
    state: present
    home: /home/backup
    ssh_key_file: .ssh/id_rsa

- name: Install duplicity to machines
  apt:
    name: duplicity
    state: present