- name: Install MySQL exporter
  apt:
    name: prometheus-mysqld-exporter

- name: Add configuration for exporter
  template:
    src: roles/mysql_exporter/files/.my.cnf
    dest: ~/.my.cnf
  notify:
    - Restart MySQL exporter

- name: Restart MySQL exporter
  service:
    name: prometheus-mysqld-exporter
    state: restarted

# - name: Create a MySQL user for exporter
#  mysql_user:
#    priv: "*.*:ALL"
#    host: "%"
#    name: "{{ exporter_user }}"
#    password: "{{ exporter_password }}"
#    login_unix_socket: /var/run/mysqld/mysqld.sock