- name: Install MySQL exporter
  apt:
    name: prometheus-mysqld-exporter

- name: Add configuration for exporter
  template:
    src: roles/mysql_exporter/files/.my.cnf
    dest: ~/.my.cnf
  notify:
    - Restart MySQL exporter

- name: Create a MySQL user for exporter
  mysql_user:
    priv: "*.*:ALL"
    host: "%"
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock