- name: Install keepalived package
  apt:
    name: keepalived

- name: Create config file
  template:
    src: roles/keepalived/templates/keepalived.conf
    dest: /etc/keepalived/keepalived.conf

- name: Configure keepalive to start on system boot
  service:
    name: keepalived
    state: enabled