---
- name: Reload daemon
  shell: systemctl daemon-reload

- name: Restart pinger
  service:
    name: pinger
    state: restarted

- name: Restart influxdb
  service:
    name: influxdb
    state: restarted