- name: Install node exporter and nginx
  apt:
    name: 
      - prometheus-node-exporter
      - nginx-core
    update_cache: yes
     
- name: Remove default nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - Restart nginx

- name: Nginx config
  template:
    src: roles/node_exporter/templates/node-exporter
    dest: /etc/nginx/sites-enabled/node-exporter
  notify:
   - Restart nginx