- name: Install prometheus
  apt:
    name: prometheus
    update_cache: yes

- name: Create user for exporters
  user:
    name: "{{ exporter_user }}"
    password: "{{ exporter_password }}"

- name: Configure linux job
  template:
    src: roles/prometheus/templates/prometheus.yml
    dest: /etc/prometheus/prometheus.yml
  notify:
    - Restart prometheus

- name: Add argument for external accessibility
  template:
    src: roles/prometheus/templates/prometheus
    dest: /etc/default/prometheus